site_name: Carry
site_description: Project documentation for Carry framework.

repo_url: https://github.com/metametadata/carry/

theme: cinder

pages:
- Home: 'index.md'
- Examples: 'examples/index.md'
- Developer Guide: 'dev-guide.md'
